# Builds on the stock precise64.box to add Oracle's JDK7.
# A good starting point for anything Java-based.
#
Vagrant.configure("2") do |config|
  config.vm.box = "ccm-precise64"
  config.vm.box_url = "/Users/zznate/vagrant-boxes/ccm-precise64.box"

  config.vm.define "ccm_cluster" do |ccm_cluster|
    ccm_cluster.vm.hostname = "ccm-cluster"
    ccm_cluster.vm.network :private_network, ip: "192.168.33.11"
  end

  # box specific parameters like memory and CPU
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end


end

