Vagrant.configure("2") do |config|
  config.vm.box = "updated-java-precise64"
  config.vm.box_url = "./updated-java-precise64.box"

  config.vm.define "jdk7base" do |jdk7base|
    jdk7base.vm.hostname = "jdk7base"
    jdk7base.vm.network :private_network, ip: "192.168.33.9"
  end

  # box specific parameters like memory and CPU
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end


end
